<a href="https://colab.research.google.com/github/nikhilkalange16/data_science_lab_SE_23/blob/main/Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Introduction to NumPy for Matrix Manipulations

NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Matrices are a core component of linear algebra, and NumPy makes it easy to perform various matrix operations efficiently.

In [1]:
import numpy as np

# Let's create a sample 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Our sample matrix A:")
print(A)

Our sample matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Calculating the Determinant of a Matrix

The determinant of a square matrix is a scalar value that can be computed from the elements of the matrix. It provides important information about the matrix, such as whether the matrix is invertible (a non-zero determinant implies invertibility).

In NumPy, the `np.linalg.det()` function is used to calculate the determinant.

In [2]:
import numpy as np

# Using the matrix A defined previously
# A = np.array([[1, 2, 3],
#               [4, 5, 6],
#               [7, 8, 9]])

determinant_A = np.linalg.det(A)

print(f"The determinant of matrix A is: {determinant_A}")

# Let's try with a matrix that is guaranteed to have a non-zero determinant for inverse calculation
B = np.array([[4, 2],
              [1, 3]])

determinant_B = np.linalg.det(B)
print("\nOur sample matrix B:")
print(B)
print(f"The determinant of matrix B is: {determinant_B}")

The determinant of matrix A is: 0.0

Our sample matrix B:
[[4 2]
 [1 3]]
The determinant of matrix B is: 10.000000000000002


### 3. Finding the Inverse of a Matrix

The inverse of a square matrix `A`, denoted as `A^-1`, is a matrix such that when multiplied by `A`, it yields the identity matrix. A matrix is invertible if and only if its determinant is non-zero.

NumPy's `np.linalg.inv()` function can be used to compute the inverse.

In [3]:
import numpy as np

# Using matrix B from the previous step (which has a non-zero determinant)
# B = np.array([[4, 2],
#               [1, 3]])

inverse_B = np.linalg.inv(B)

print("The inverse of matrix B is:")
print(inverse_B)

# Verify the inverse: B @ inverse_B should be close to the identity matrix
identity_check = B @ inverse_B
print("\nB @ B_inv (should be close to identity matrix):")
print(identity_check)
print("\nNote: Due to floating point precision, the values might not be exactly 0 or 1, but very close.")

The inverse of matrix B is:
[[ 0.3 -0.2]
 [-0.1  0.4]]

B @ B_inv (should be close to identity matrix):
[[ 1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00]]

Note: Due to floating point precision, the values might not be exactly 0 or 1, but very close.


### 4. Solving a System of Linear Equations using Matrix Methods

A system of linear equations can be represented in matrix form as `Ax = b`, where `A` is the coefficient matrix, `x` is the vector of variables, and `b` is the constant vector.

To solve for `x`, we can use `x = A^-1 * b`. NumPy provides `np.linalg.solve()` which is more efficient and numerically stable than calculating the inverse explicitly and then multiplying.

Let's consider the system:

$4x + 2y = 10$

$x + 3y = 7$

In [4]:
import numpy as np

# Define the coefficient matrix A
A_coeffs = np.array([[4, 2],
                     [1, 3]])

# Define the constant vector b
b_constants = np.array([10, 7])

print("Coefficient matrix A:")
print(A_coeffs)
print("\nConstant vector b:")
print(b_constants)

# Solve the system of equations
x_solution = np.linalg.solve(A_coeffs, b_constants)

print("\nThe solution for [x, y] is:")
print(x_solution)

print(f"\nSo, x = {x_solution[0]:.2f} and y = {x_solution[1]:.2f}")

# You can verify the solution by plugging x and y back into the original equations:
# 4*(1.7) + 2*(1.6) = 6.8 + 3.2 = 10
# 1*(1.7) + 3*(1.6) = 1.7 + 4.8 = 6.5 (close to 7 due to float precision)

Coefficient matrix A:
[[4 2]
 [1 3]]

Constant vector b:
[10  7]

The solution for [x, y] is:
[1.6 1.8]

So, x = 1.60 and y = 1.80
